"""VectorUpserter — shared chunk IDs + idempotent vector store writes.

Receives chunks paired with their dense vectors and writes them to a
BaseVectorStore via upsert, using ``chunk.id`` as the vector store id.

ID contract:
- The vector store id IS ``chunk.id`` (generated by DocumentChunker as
  ``{doc_id}_{index:04d}_{content_hash8}``), which is already deterministic
  and content-derived.
- Using ``chunk.id`` keeps the vector store and the BM25 index keyed by the
  SAME id, so the SparseRetriever can resolve BM25 hits back to chunk text via
  ``vector_store.get_by_ids()``. (A previously separate hash scheme caused the
  two stores to diverge, breaking sparse retrieval.)
- Same chunk content/position -> same id -> re-ingest overwrites (idempotent).
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from src.core.types import Chunk
from src.libs.vector_store.base_vector_store import VectorRecord

if TYPE_CHECKING:
    from src.core.trace.trace_context import TraceContext
    from src.libs.vector_store.base_vector_store import BaseVectorStore

logger = logging.getLogger(__name__)


class VectorUpserter:
    """Generate stable IDs and upsert dense vectors idempotently."""

    def __init__(self, vector_store: "BaseVectorStore"):
        if vector_store is None:
            raise ValueError("VectorUpserter requires a BaseVectorStore instance")
        self._store = vector_store

    @staticmethod
    def make_vector_id(chunk: Chunk) -> str:
        """Return the vector store id for a chunk.

        This is simply ``chunk.id`` — the canonical, deterministic,
        content-derived id assigned by DocumentChunker. Keeping the vector
        store keyed by ``chunk.id`` ensures it shares the same id space as the
        BM25 index, so sparse retrieval can resolve hits back to chunk text.
        """
        return chunk.id

    def upsert(
        self,
        chunks: list[Chunk],
        dense_vectors: list[list[float]],
        trace: "TraceContext | None" = None,
    ) -> list[str]:
        """Build records with stable IDs and upsert them, preserving order.

        Args:
            chunks: Chunks to store.
            dense_vectors: Dense vectors aligned with chunks (same length/order).
            trace: Optional trace context.

        Returns:
            List of generated vector IDs, in input order.

        Raises:
            ValueError: if chunks and dense_vectors lengths differ.
        """
        if len(chunks) != len(dense_vectors):
            raise ValueError(
                f"chunks ({len(chunks)}) and dense_vectors "
                f"({len(dense_vectors)}) must have equal length"
            )

        if trace:
            trace.start_stage("vector_upserter")

        if not chunks:
            if trace:
                trace.end_stage(details={"upserted": 0})
            return []

        records: list[VectorRecord] = []
        ids: list[str] = []
        for chunk, vector in zip(chunks, dense_vectors):
            vid = self.make_vector_id(chunk)
            ids.append(vid)
            records.append(
                VectorRecord(
                    id=vid,
                    vector=vector,
                    text=chunk.text,
                    metadata=dict(chunk.metadata),
                )
            )

        count = self._store.upsert(records, trace=trace)
        logger.info("Upserted %d vectors", count)

        if trace:
            trace.end_stage(details={"upserted": count})

        return ids
